// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/roppenlabs/rapid-product-catalog/internal/config"
	"github.com/roppenlabs/rapid-product-catalog/internal/health"
	"github.com/roppenlabs/rapid-product-catalog/internal/product"
	"github.com/roppenlabs/rapid-product-catalog/internal/server"
	"github.com/roppenlabs/rapid-product-catalog/internal/utils"
)

// Injectors from di.go:

func InitDependencies() (ServerDependencies, error) {
	configConfig := config.GetConfig()
	serverServer := server.NewServer(configConfig)
	handler := health.NewHandler()
	dbInstance, err := utils.NewDBInstance(configConfig)
	if err != nil {
		return ServerDependencies{}, err
	}
	productRepository := product.NewRepository(dbInstance)
	service := product.NewService(configConfig, productRepository)
	productHandler := product.NewHandler(service)
	handlers := server.Handlers{
		HealthHandler:        handler,
		ProductUploadHandler: productHandler,
	}
	serverDependencies := ServerDependencies{
		config:   configConfig,
		server:   serverServer,
		handlers: handlers,
	}
	return serverDependencies, nil
}

// di.go:

type ServerDependencies struct {
	config   config.Config
	server   *server.Server
	handlers server.Handlers
}
